version: "3.9"

services:
  api:
    build: ./server
    expose:
      - "8000"
    restart: always
    env_file: ./server/.env

    networks:
      - backend
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - api
    restart: always
    networks:
      - backend

networks:
  backend:
