global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus2.pruebasinventario.me']
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'api'
    #metrics_path: '/apiv3/metrics'
    static_configs:
      - targets: ['app2.pruebasinventario.me']
  # - job_name: 'grafana'
  #   static_configs:
  #     - targets: ['grafana2.pruebasinventario.me']