
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    # strategy:
    #   matrix:
    #     node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: npm ci
    #- run: npm test
      #working-directory: ./server
      - run: |
          touch ./server/.env
          echo "${{secrets.PROD_ENV_NCAPAS }}" > ./server/.env
          chmod +x ./server/start.sh
          ./server/start.sh
          echo "COMPOSE_HTTP_TIMEOUT=200" >> $GITHUB_ENV  # Establece el valor a 200 segundos
          sudo docker-compose up --build -d 

    #- run: pm2 restart BackendNCapas
      



