name: BACKEND

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  start:
    name: PULL
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
       - run:
        touch .env
        echo "{{secrets.PROD_ENV_FILE }}" > .env


  env:
    name: SET ENV
    needs: [start]
    runs-on: self-hosted
    steps:
      - name: ENV BACK
        working-directory: ./server
        run: |
          touch .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_SERVER=${{ secrets.DB_SERVER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DIALECT=${{ secrets.DB_DIALECT }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env


  # build:
  #   name: DEPLOY
  #   needs: [env]
  #   runs-on: self-hosted
  #   steps:
  #     - name: build
  #       working-directory: ./
  #       run: docker-compose up --build -d
