name: BACKEND

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  start:
    name: PULL
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

  env:
    name: SET ENV
    needs: [start]
    runs-on: self-hosted
    steps:
      - name: ENV BACK
        working-directory: ./server
        run: |
          touch .env
          echo DB_USER=${{ secrets.DB_USER }} >> .env
          echo DB_SERVER=${{ secrets.DB_SERVER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_DIALECT=${{ secrets.DB_DIALECT }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env


         # Instala Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

    # Instala Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose 
          

  build:
    name: DEPLOY
    needs: [env]
    runs-on: self-hosted
    steps:
      - name: build
        run: docker-compose up --build -d
